### ISSUE TITLE
publish - PyPI

### ISSUE THREAD

**Issue by sometheycallme** [Jfach/autostager#3]
@Jfach 
http://docs.python-guide.org/en/latest/shipping/packaging/

I haven't messed with publishing a package.

The pattern that @jumanjiman uses is to push to rubygems.org via Circle.  Might be worthwhile to consider it.

https://github.com/jumanjihouse/autostager/blob/master/script/push.sh
https://github.com/jumanjihouse/autostager/blob/master/circle.yml

**Comment by jfach** [comment]
Tim,

I've published packages to PyPl in the past for use with PIP. Shouldn't be a problem.

Jordan

Sent from my iPhone

On May 21, 2016, at 11:59 AM, Tim Kropp <notifications@github.com<mailto:notifications@github.com>> wrote:

@Jfachhttps://github.com/Jfach
http://docs.python-guide.org/en/latest/shipping/packaging/

I haven't messed with publishing a package.

The pattern that @jumanjimanhttps://github.com/jumanjiman uses is to push to rubygems.orghttp://rubygems.org via Circle. Might be worthwhile to consider it.

https://github.com/jumanjihouse/autostager/blob/master/script/push.sh
https://github.com/jumanjihouse/autostager/blob/master/circle.yml

##

**Comment by sometheycallme** [comment]
Cool.  Yes "pip install autostager" would be nice to ease Implemntation in a container for example.

**Comment by jfach** [comment]
Consider it done.

Sent from my iPhone

On May 21, 2016, at 5:31 PM, Tim Kropp <notifications@github.com<mailto:notifications@github.com>> wrote:

Cool. Yes "pip install autostager" would be nice to ease Implemntation in a container for example.

##

**Comment by sometheycallme** [comment]
Once you are done with PIP, We can work to add another docker container in cleanerbot using it.

I put a readme in the https://github.com/cleanerbot/ansible-security repo showing this design.

**Comment by jfach** [comment]
:boom: Done! Go ahead and  `pip install autostager`.

**Comment by sometheycallme** [comment]
Awesome I'll look at this right away.

**Comment by jfach** [comment]
@sometheycallme make sure you take note of the release version if you pip install. I'm still squashing bugs as we speak. Let me know if you run into any errors.

**Comment by sometheycallme** [comment]
Thanks.   I'm pulling in latest

**Comment by sometheycallme** [comment]
```
Executing busybox-1.24.2-r8.trigger
Executing ca-certificates-20160104-r4.trigger
OK: 78 MiB in 29 packages
Requirement already up-to-date: pip in /usr/lib/python2.7/site-packages
Collecting autostager
  Downloading autostager-0.1.21.tar.gz
Collecting github3.py (from autostager)
  Downloading github3.py-0.9.5-py2.py3-none-any.whl (109kB)
Collecting requests>=2.0 (from github3.py->autostager)
  Downloading requests-2.10.0-py2.py3-none-any.whl (506kB)
Collecting uritemplate.py>=0.2.0 (from github3.py->autostager)
  Downloading uritemplate.py-0.3.0.tar.gz
Installing collected packages: requests, uritemplate.py, github3.py, autostager
  Running setup.py install for uritemplate.py: started
    Running setup.py install for uritemplate.py: finished with status 'done'
  Running setup.py install for autostager: started
    Running setup.py install for autostager: finished with status 'done'
Successfully installed autostager-0.1.21 github3.py-0.9.5 requests-2.10.0 uritemplate.py-0.3.0
 ---> 499e1b02d77f
```

**Comment by jfach** [comment]
Perfect. All the requirements were automatically installed.
